# Spring Configuration
spring:
  # MySQl Database Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_management_dev?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  # Shiro Config
shiro:
  loginUrl: /user/index
  unauthorizedUrl: /user/index


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # log for mysql-plus